FROM openjdk:17
COPY target/submissionController-0.0.1-SNAPSHOT.jar usr/src/app/submissionController-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "usr/src/app/submissionController-0.0.1-SNAPSHOT.jar"]
